/**
 * Compose the Discord webhook payload for a Facebook post.
 * The title is the first sentence of the message, and the body is the rest.
 * If an image is available, it is included in the embed.
 */

export interface FacebookPost {
    message?: string;
    permalink_url?: string;
    full_picture?: string;
    created_time?: string;
    [key: string]: any;
}

export interface DiscordEmbed {
    url: string;
    description: string;
    color: number;
    timestamp?: string;
    image?: { url: string };
}

export interface DiscordWebhookPayload {
    content: string;
    embeds: DiscordEmbed[];
}

/**
 * Compose the Discord webhook payload for a Facebook post.
 * @param post - The Facebook post object.
 * @param color - The color of the embed (default: #4289db).
 * @returns The Discord webhook payload.
 */
export async function composeDiscordWebhookMessage(
    post: FacebookPost,
    color: number = 0x4289db
): Promise<DiscordWebhookPayload> {
    // Fallbacks for missing fields
    const content = post.message || "";
    const url = post.permalink_url || "";
    const image = post.full_picture || null;

    // Extract the title: first sentence before a dot or newline
    let title: string | null = content
        ? content.split(/[\.\n]/)[0].trim()
        : null;
    if (!title) title = null;

    let description = "";
    if (content) {
        description = `[**${title}**](${url})\n\n${content}`;
    } else if (image) {
        description = `[View on Facebook](${url})\n\n📷 New announcement with image.`;
    } else {
        description = `[View on Facebook](${url})`;
    }

    // Format the timestamp to a more readable format (not used in payload, but kept for reference)
    let formattedTime = "";
    if (post.created_time) {
        const date = new Date(post.created_time);
        formattedTime = date.toLocaleString("en-US", {
            year: "numeric",
            month: "short",
            day: "2-digit",
            hour: "2-digit",
            minute: "2-digit",
            hour12: true,
        });
    }

    // Discord webhook payload structure
    const payload: DiscordWebhookPayload = {
        content: "",
        embeds: [
            {
                url: url,
                description: description,
                color: color,
                timestamp: post.created_time,
            },
        ],
    };

    // If the post has an image, add it to the embed
    if (image) {
        payload.embeds[0].image = { url: image };
    }

    return payload;
}

/**
 * Send a message payload to a Discord webhook URL.
 * @param webhookUrl - The Discord webhook URL.
 * @param payload - The payload generated by composeDiscordWebhookMessage.
 */
export async function sendDiscordWebhookMessage(
    webhookUrl: string,
    payload: DiscordWebhookPayload
): Promise<void> {
    const res = await fetch(webhookUrl, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload),
    });
    if (!res.ok) {
        console.error("Failed to send Discord webhook:", await res.text());
    }
}
